DROP TABLE IF EXISTS dog CASCADE;
CREATE TABLE dog
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    sex CHAR(1),
    age INT,
    breed VARCHAR(255),
    weight FLOAT,
    location VARCHAR(255),
    photo VARCHAR(255),
    PRIMARY KEY (id)
);

INSERT INTO dog
VALUES
    ('52718', 'Houston', 'M', '3', 'Shepard', '52', 'Madison, WI', 'https://cdn.britannica.com/22/234622-050-4D6BD081/Australian-shepherd-dog-red-merle.jpg'),
    ('25819', 'Coco', 'F', '5', 'Bulldog', '43', 'Chicago, IL', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToS2sXpoT7iaX2ab9fJBKWwE5OeWVWNoE1qQ&usqp=CAU'),
    ('16920', 'Gary', 'M', '2', 'Retriever', '71', 'Madison, WI', 'https://t2.ea.ltmcdn.com/en/posts/4/0/9/10_things_you_should_know_about_golden_retrievers_904_600_square.jpg'),
    ('71289', 'Max', 'M', '6', 'Husky', '55', 'Madison, WI', 'https://www.insidedogsworld.com/wp-content/uploads/2016/12/husky10.jpg'),
    ('42911', 'Lucy', 'F', '7', 'Poodle', '51', 'Chicago, IL', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6ZJ--97diNN7pzOXtD5QHQMqv5cFy3fhJZFCX80H0Yh6TSs-7FRrAwnt1xKqwnLT84k4&usqp=CAU'),
    ('62214', 'Cooper', 'M', '3', 'Chihuahua', '5', 'Chicago, IL', 'https://cdn.britannica.com/44/233244-050-A65D4571/Chihuahua-dog.jpg'),
    ('82103', 'Penny', 'F', '5', 'Corgi', '24', 'Chicago, IL', 'https://www.akc.org/wp-content/uploads/2017/11/Pembroke-Welsh-Corgi-standing-outdoors-in-the-fall.jpg'),
    ('32149', 'Rooster', 'M', '4', 'Rottweiler', '121', 'Madison, WI', 'https://cdn.britannica.com/69/234469-050-B883797B/Rottweiler-dog.jpg'),
    ('91215', 'Toby', 'M', '2', 'Hound', '31', 'Chicago, IL', 'https://i.pinimg.com/originals/b6/bf/98/b6bf9801b7ff322c09c355a83aef14d4.png'),
    ('48921', 'Jasper', 'M', '4', 'Dachshund', '27', 'Madison, WI', 'https://cdn.britannica.com/81/12481-004-1AD2693C.jpg')
;